on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Runs nbb tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        uses: logseq/graph-validator@main
